### ISSUE TITLE
Move data types to later on in first session

### ISSUE THREAD

**Issue by jayware9** [ScotGovAnalysis/intro_to_r#15]
https://github.com/DataScienceScotland/intro_to_r/blob/8a8e5bd0dbf7db188065fcceb5e45110567f5ffa/session1/intro_to_r_training.Rmd#L509

This feels quite advanced compared to what follows. Data types is something that probably needs mentioning, but for someone with little coding background is may be challenging. We could move it to after the data wrangling section, so folks at least have had a chance to play around a bit with data first?

**Comment by irisoren-sg** [comment]
Decide where to put this after the first session

**Comment by irisoren-sg** [comment]
There have not been issues with this during sessions. Revisit if we see that students struggle
