### ISSUE TITLE
Session 1: standardising iris dataset lines

### ISSUE THREAD

**Issue by graemelloydsg** [ScotGovAnalysis/intro_to_r#41]
Currently the iris dataset section mixes between reading the base R dataset iris and the iris_petals.csv dataset as well as between a data frame and a tibble. Instead this should probably focus on tibbles (to meet the standardisation of tidyverse usage) and hence should read in a new iris file rather than use a data() call.

**Comment by irisoren-sg** [comment]
Agreed @graemelloydsg  Also, if we read data, we should make all variables/columns follow the tidyverse styleguide

**Comment by graemelloydsg** [comment]
Thanks Iris. Good suggestion!

**Comment by irisoren-sg** [comment]
#34 already an issue, so can be closed in the same PR
