### ISSUE TITLE
What is R intro references MoJ

### ISSUE THREAD

**Issue by jayware9** [ScotGovAnalysis/intro_to_r#97]
We should probably change this to Scottish Government. And reference to 5 years, maybe should be updated to 10? 

https://github.com/ScotGovAnalysis/intro_to_r/blob/e13a0f0d6158afa301461478dd2024c6491c6f64/session1/intro_to_r_training_incomplete.Rmd#L73

**Comment by Talexis77** [comment]
I agree, I think some of these materials came originally from the MoJ which is where that reference might have come from? Also makes sense to change it to 10 years I think

**Comment by jayware9** [comment]
@josh-bird6 I noticed there's still some references to MoJ in session 1 that probably need updating. Though not urgent so should we leave until after this round of training?

**Comment by josh-bird6** [comment]
Thanks very much for flagging this @jayware9. Just going through session 1 materials myself now and agree that needs updating - there is also a link in there which doesn't work. Let's discuss at our pre-meet this afternoon, and in the meantime I'll continue looking to see if anything else needs addressing.
